config/routes.rb
Rails.application.routes.draw do

  get 'comentario/index'

  get 'alumbrado/index'

  get 'parques/index'

  get 'pavimento/index'

  get 'playlist/show'
  
  get 'users/politica'
  

  #se agrega la ruta de devise para users
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  get  "omniauth/:provider/callback"  => "devise_token_auth/omniauth_callbacks#redirect_callbacks"
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], as: :finish_signup
  resources :reports, only: [:show, :new, :create, :update] do
    
    member do
      post "add_vote"
      post "remove_vote"
      post "add_comment"
      post "approve"
      post "re_open"
      post "complete"
      delete "delete"
    end
    
    collection do
      post "add_like" => "reports#add_like"
      post "remove_like" => "reports#remove_like"
    end
  end

  get 'main' => 'main#index'
  get "view_notification" => "main#view_notification"

  namespace :api do
    namespace :v1 do
      #Playlist related routs
      get 'playlist', to: "playlist#show"

      # Report related routes
      get 'reports', to: "report_api#index"
      get 'reports/:id', to: "report_api#show"
      post 'reports', to: "report_api#create"
      put 'reports/:id', to: "report_api#update"
      patch 'reports/:id', to: "report_api#update"
      post 'reports/:id/add_vote', to: 'report_api#add_vote'
      post 'reports/:id/remove_vote', to: 'report_api#remove_vote'
      get 'reports/:id/comments', to: 'report_api#comments'
      post 'reports/:id/add_comment', to: 'report_api#add_comment'
      post 'reports/:id/add_vote', to: 'report_api#add_vote'
      delete 'reports/:id/remove_vote', to: 'report_api#remove_vote'
      post 'reports/:id/propose_as_completed', to: 'report_api#propose_as_completed'
      # Sessions related routes -- DEPRECATED
      # devise_scope :user do
      #   post 'sessions' => 'sessions#create', as: 'login'
      #   delete 'sessions' => 'sessions#destroy', as: 'logout'
      # end
      
      # Contacts related routes
      get 'contacts', to: 'contact_api#index'
      
      # Notifications related routes
      get 'notifications', to: 'notifications_api#recent_notifications'
      post 'notifications/:id/mark_as_read', to: 'notifications_api#mark_as_read'
      
      # Comments related routes
      post 'comments/:id/like', to: 'comment_api#like'
      delete 'comments/:id/unlike', to: 'comment_api#unlike'
      post 'comments/:id/flag', to: 'comment_api#flag'
      
      # User related routes
      post 'user/change_picture', to: 'user_info_api#change_picture'
      get 'user/stats', to: 'user_info_api#stats'

      # Api auth routes
      post 'auth/signin', to: 'auth_api#signin'
      post 'auth/signup', to: 'auth_api#signup'
      post 'auth/finish_signup', to: 'auth_api#finish_signup'
      post 'auth/recover', to: 'auth_api#recover'
      delete 'auth/signout_all', to: 'auth_api#signout_all'
    end
  end  
  

  
  scope "administration" do
    resources :users
    resources :contacts
    resources :reports
    get 'limpia' => "limpia#index"
    get 'pavimento' => "pavimento#index"
    get 'alumbrado' => "alumbrado#index"
    get 'parques' => "parques#index"
    get 'estadistica' => "estadistica#index"
    get 'comentario' => "comentario#index"
    get "reports" => "reports#index"

    
    
  end
  
  root "home#index"
  
end

app/controllers/administration_controller.rb
class AdministrationController < ApplicationController
  before_action :user_is_admin?
  
  def reports
    @user = current_user
    #@reports = Report.all
  end
  
  def users
    @user = current_use
    #@users = User.all
  end
end

app/helpers/administration_helper.rb
module AdministrationHelper
end

app/views/administration/_admin_menu.html.haml
.row{ style: "margin-top: 60px;" }
  .container
    .row
      #admin-title.col-xs-12.orange
        Panel de administración
      #admin-menu.col-xs-12
        %ul.nav.nav-pills
          - if current_user.departamento == 0
            %li{ role: "presentation", class: active == "reports" ? "active" : nil }
              = link_to "Reportes", "/administration/reports"
          - if current_user.departamento == 0
            %li{ role: "presentation", class: active == "users" ? "active" : nil }
              = link_to "Usuarios", users_path
          - if current_user.departamento == 0
            %li{ role: "presentation", class: active == "directory" ? "active" : nil }
              = link_to "Directorio", contacts_path
          - if current_user.departamento == 0 || current_user.departamento == 1
            %li{ role: "presentation", class: active == "limpia" ? "active" : nil }
              = link_to "Limpia", limpia_path
          - if current_user.departamento == 0 || current_user.departamento == 2
            %li{ role: "presentation", class: active == "pavimento" ? "active" : nil }
              = link_to "Pavimento", pavimento_path
          - if current_user.departamento == 0 || current_user.departamento == 3
            %li{ role: "presentation", class: active == "parques" ? "active" : nil }
              = link_to "Parques", parques_path
          - if current_user.departamento == 0 || current_user.departamento == 4
            %li{ role: "presentation", class: active == "alumbrado" ? "active" : nil }
              = link_to "Alumbrado", alumbrado_path
          - if current_user.departamento == 0
            %li{ role: "presentation", class: active == "estadistica" ? "active" : nil }
              = link_to "Estadistica", "/administration/estadistica"
          - if current_user.departamento == 0
            %li{ role: "presentation", class: active == "comentarios" ? "active" : nil }
              = link_to "Comentarios", "/administration/comentario"

app/views/administration/_admin_menu_limpia.html.haml
.row{ style: "margin-top: 60px;" }
  .container
    .row
      #admin-title.col-xs-12.orange
        Panel de administración
        = current_user
      #admin-menu.col-xs-12
        %ul.nav.nav-pills
          %li{ role: "presentation", class: active == "directory" ? "active" : nil }
            = link_to "Limpia", limpia_path

app/views/administration/directory.html.haml
= render "main/menu"
= render "admin_menu", active: "directory"
.row
  .container
    .row
      .form-div.col-xs-12
        = link_to "Agregar contacto", new_contact_path, class: "btn btn-default", style: "margin-top: 30px;"
    .row
      .col-xs-12
        %table.table.table-striped.info-table
          %thead
            %tr
              %th<
                ID
              %th<
                Nombre
              %th<
                Teléfono
          %tbody
            - @contacts.each do |contact|
              %tr
                %td<
                  = contact.id
                %td<
                  = contact.name
                %td<
                  = contact.phone

app/views/administration/new_contact.html.haml
= render "main/menu"
.row{ style: "margin-top: 60px; padding-bottom: 70px;" }
  .container
    .row
      .col-xs-4.orange{ style: "font-size: 40px; font-weight: 300; margin-top: 30px;" }
        Agregar contacto
    .row
      .col-xs-12{ style: "margin-top: 20px;" }
        = form_tag(create_contact_path, method: :post) do
          .row
            .col-xs-3
              = label_tag :name, "Nombre", class: "darkest-gray"
              = text_field_tag :name, "", class: "form-control"
            .col-xs-3
              = label_tag :phone, "Teléfono", class: "darkest-gray"
              = text_field_tag :phone, "", class: "form-control"
            .col-xs-6{ style: "margin-top: 25px;" }
              = submit_tag "Crear", class: "btn btn-primary"
              = link_to "Cancelar", administration_directory_path, class: "btn btn-danger", style: "margin-left: 10px;"