config/routes.rb
Rails.application.routes.draw do

  get 'comentario/index'

  get 'alumbrado/index'

  get 'parques/index'

  get 'pavimento/index'

  get 'playlist/show'
  
  get 'users/politica'
  

  #se agrega la ruta de devise para users
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  get  "omniauth/:provider/callback"  => "devise_token_auth/omniauth_callbacks#redirect_callbacks"
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], as: :finish_signup
  resources :reports, only: [:show, :new, :create, :update] do
    
    member do
      post "add_vote"
      post "remove_vote"
      post "add_comment"
      post "approve"
      post "re_open"
      post "complete"
      delete "delete"
    end
    
    collection do
      post "add_like" => "reports#add_like"
      post "remove_like" => "reports#remove_like"
    end
  end

  get 'main' => 'main#index'
  get "view_notification" => "main#view_notification"

  namespace :api do
    namespace :v1 do
      #Playlist related routs
      get 'playlist', to: "playlist#show"

      # Report related routes
      get 'reports', to: "report_api#index"
      get 'reports/:id', to: "report_api#show"
      post 'reports', to: "report_api#create"
      put 'reports/:id', to: "report_api#update"
      patch 'reports/:id', to: "report_api#update"
      post 'reports/:id/add_vote', to: 'report_api#add_vote'
      post 'reports/:id/remove_vote', to: 'report_api#remove_vote'
      get 'reports/:id/comments', to: 'report_api#comments'
      post 'reports/:id/add_comment', to: 'report_api#add_comment'
      post 'reports/:id/add_vote', to: 'report_api#add_vote'
      delete 'reports/:id/remove_vote', to: 'report_api#remove_vote'
      post 'reports/:id/propose_as_completed', to: 'report_api#propose_as_completed'
      # Sessions related routes -- DEPRECATED
      # devise_scope :user do
      #   post 'sessions' => 'sessions#create', as: 'login'
      #   delete 'sessions' => 'sessions#destroy', as: 'logout'
      # end
      
      # Contacts related routes
      get 'contacts', to: 'contact_api#index'
      
      # Notifications related routes
      get 'notifications', to: 'notifications_api#recent_notifications'
      post 'notifications/:id/mark_as_read', to: 'notifications_api#mark_as_read'
      
      # Comments related routes
      post 'comments/:id/like', to: 'comment_api#like'
      delete 'comments/:id/unlike', to: 'comment_api#unlike'
      post 'comments/:id/flag', to: 'comment_api#flag'
      
      # User related routes
      post 'user/change_picture', to: 'user_info_api#change_picture'
      get 'user/stats', to: 'user_info_api#stats'

      # Api auth routes
      post 'auth/signin', to: 'auth_api#signin'
      post 'auth/signup', to: 'auth_api#signup'
      post 'auth/finish_signup', to: 'auth_api#finish_signup'
      post 'auth/recover', to: 'auth_api#recover'
      delete 'auth/signout_all', to: 'auth_api#signout_all'
    end
  end  
  

  
  scope "administration" do
    resources :users
    resources :contacts
    resources :reports
    get 'limpia' => "limpia#index"
    get 'pavimento' => "pavimento#index"
    get 'alumbrado' => "alumbrado#index"
    get 'parques' => "parques#index"
    get 'estadistica' => "estadistica#index"
    get 'comentario' => "comentario#index"
    get "reports" => "reports#index"

    
    
  end
  
  root "home#index"
  
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :identities
  has_many :session_ids

  TEMP_EMAIL_PREFIX = 'change@me'
  TEMP_EMAIL_REGEX = /\Achange@me/

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :confirmable, :recoverable, :registerable, :trackable, :timeoutable, :omniauthable, omniauth_providers: [:facebook,:twitter, :google_oauth2]
  #quite :validatable
  
  validates_format_of :email, without: TEMP_EMAIL_REGEX, on: :update

  has_many :reports, dependent: :destroy
  has_many :affectation_votes
  has_many :comments
  has_many :likes
  has_many :activity_records
  
  validates :name, presence: true
  #validates :email, uniqueness: true
  validates :username, uniqueness: true
  #validates :gender, presence: true
  #validates :birthdate, presence: true
  has_attached_file :avatar
  # validates_attachment :avatar, content_type: { content_type: ["image/jpeg", "image/gif", "image/png", "image/bmp"] }, size: { less_than: 1.megabytes }
  do_not_validate_attachment_file_type :avatar

  def avatar_url
    omniauth_image || (avatar.url =~ /missing/ ? nil : avatar.url)
  end

  def report_count
    reports.count
  end

  def comment_count
    comments.count
  end

  def level
    number_of_reports = reports.count
    if number_of_reports >= 60
      return 9
    elsif number_of_reports >= 45
      return 8
    elsif number_of_reports >= 35
      return 7
    elsif number_of_reports >= 25
      return 6
    elsif number_of_reports >= 20
      return 5
    elsif number_of_reports >= 15
      return 4
    elsif number_of_reports >= 10
      return 3
    elsif number_of_reports >= 5
      return 2
    else
      return 1
    end
  end

  def since
    created_at.strftime('%d/%m/%Y')
  end

  def get_uid_for_provider(provider)
    if identities.count > 0
      identities.find_by_provider(provider).uid
    else
      nil
    end
  end

  def self.find_by_uid_for_provider(uid, provider)
    identity = Identity.where(provider: provider, uid: uid)
    if identity
      identity.user
    else
      nil
    end
  end

  def self.find_for_oauth(auth, signed_in_resource = nil)

    # Get the identity and user if they exist
    identity = Identity.find_for_oauth(auth)

    # If a signed_in_resource is provided, it always overrides the existing user
    # to prevent the identity beign locked with accidentally created accounts.
    # Note that this may leave zombie accounts (with no associated identity) which
    # can be cleaned up at a later date.
    user = signed_in_resource ? signed_in_resource : identity.user

    # Create the user if needed
    if user.nil?

      # Get the existing user by email if the provider gives us a verified email.
      # If no verified email was provided we assign a temporary email and ask the 
      # user to verify it on the next step via UsersController.finish_signup
      if auth.provider == "google_oauth2" || "facebook" 
        email = auth.info.email
      else
        email_is_verfied = auth.info.email && (auth.info.verified || auth.info.verified_email)
        email = auth.info.email if email_is_verfied
        user = User.where( email: email ).first if email
      end
      # Create the user if it is a new registration
      if user.nil?
          # logger.info auth
          user = User.new(
            name: auth.extra.raw_info.name,
            email: email ? email : "#{TEMP_EMAIL_PREFIX}-#{auth.uid}-#{auth.provider}.com",
            password: Devise.friendly_token[0,20],
            omniauth_image: auth.info.image
          )
          user.skip_confirmation!
          Logger.new("PRUEBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA")
          user.save!
        end
      end

      # Associate the identity with the user if needed
      if identity.user != user
        identity.user = user
        identity.save!
      end
      user
    end

    def email_verified?
      self.email && self.email !~ TEMP_EMAIL_REGEX
    end
    
    #--------------------------------
      attr_accessor :login
#--------------------------------
    def self.find_for_database_authentication(warden_conditions)
      conditions = warden_conditions.dup
      if login = conditions.delete(:login)
        where(conditions.to_hash).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
      else
        where(conditions.to_hash).first
      end
    end
#----------------------------------
# implementacion para google
def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(:email => data["email"]).first

    # Uncomment the section below if you want users to be created if they don't exist
    unless user
        user = User.create(name: data["name"],
            email: data["email"],
            password: Devise.friendly_token[0,20]
        )
    end
    user
end

#-----------------------------------------------------------------------------

    
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :finish_signup]
  before_action :user_is_admin?, except: [:finish_signup]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    @user.is_admin = true
    @user.confirmed_at = Time.now

    respond_to do |format|
      if @user.save
        #se agrega codigo de prueba
        #ExampleMailer.sample_email(@user).deliver
        #se cierra codigo de preuba
        format.html { redirect_to users_path, notice: 'Se ha creado un nuevo administrador satisfactoriamente!' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET/PATCH /users/:id/finish_signup
  def finish_signup
    if request.patch? && params[:user]
      if @user.update(user_params)
        @user.identities.each do |p|
          if p.provider=="facebook"
            @user.skip_confirmation!
            sign_in(@user, bypass: true)
            redirect_to root_path, notice: 'Tu perfil ha sido actualizado.'
          elsif p.provider == "google_oauth2"
            @user.skip_confirmation!
            sign_in(@user, bypass: true)
            redirect_to root_path, notice: 'Tu perfil ha sido actualizado.'
          elsif p.provider == "google"
            @user.skip_confirmation!
            sign_in(@user, bypass: true)
            redirect_to root_path, notice: 'Tu perfil ha sido actualizado.'  
          elsif p.provider  == "twitter"
           @user.send_confirmation_instructions
            redirect_to root_path, notice: 'Se te ha enviado un correo de confirmación.'
            
          else

           @user.send_confirmation_instructions
            redirect_to root, notice: 'Se te ha enviado un correo de confirmación.'
          end     
        end
      else
        @show_errors = true
        logger.info(@user.errors)
      end
    end   
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
  #  def user_params
   #   params.require(:user).permit(:name, :username, :email, :password, :birthdate, :gender)
    #end
    def user_params
      accessible = [ :name, :email , :username, :gender, :birthdate] # se agrega username como parametro valido 
      accessible << [ :password, :password_confirmation ] unless params[:user][:password].blank?
      params.require(:user).permit(accessible)
    end
    
end

app/views/users/_form.html.haml
.row
  .col-xs-12
    = form_for @user do |f|
      .row{ style: "margin-top: 20px;" }
        .col-xs-3
          = f.label :name, "Nombre", class: "darkest-gray"
          = f.text_field :name, class: "form-control"
      .row
        .col-xs-3
          = f.label :username, "Nombre de usuario", class: "darkest-gray"
          = f.text_field :username, class: "form-control"
      .row
        .col-xs-3
          = f.label :email, "Correo electrónico", class: "darkest-gray"
          = f.text_field :email, class: "form-control"
      .row
        .col-xs-3
          = f.label :password, "Contraseña (6 caracteres mínimo)", class: "darkest-gray"
          = f.password_field :password, autocomplete: "off", class: "form-control"
      .row
        .col-xs-3
          = f.label :password_confirmation, "Repetir contraseña", class: "darkest-gray"
          = f.password_field :password_confirmation, autocomplete: "off", class: "form-control"
      .row
        .col-xs-12
          = f.label :birthdate, "Fecha de nacimiento", class: "darkest-gray", style: "display: block;"
          = select_tag :day, options_for_select((1..31).map{|e| [e, e]}), prompt: "Día", class: "form-control", style: "width: 80px; display: inline-block;"
          = select_tag :month, options_for_select([["Enero", 1], ["Febrero", 2], ["Marzo", 3], ["Abril", 4], ["Mayo", 5], ["Junio", 6], ["Julio", 7], ["Agosto", 8],
            ["Septiembre", 9], ["Octubre", 10], ["Noviembre", 11], ["Diciembre", 12]]), prompt: "Mes", class: "form-control", style: "width: 120px; display: inline-block; margin-left: 5px;"
          = select_tag :year, options_for_select((1950..2000).map{|e| [e, e]}), prompt: "Año", class: "form-control", style: "width: 80px; display: inline-block; margin-left: 5px;"
          = f.hidden_field :birthdate
      .row
        .col-xs-3
          = f.label :gender, "Género", class: "darkest-gray"
          = f.select :gender, options_for_select([["Masculino", "M"], ["Femenino", "F"]], selected: @user.gender), { prompt: "Género" }, class: "form-control"
      .row
        .col-xs-6{ style: "margin-top: 25px;" }
          = f.submit "Crear", class: "btn btn-orange", id: "create-user-btn"
          = link_to "Cancelar", users_path, class: "btn btn-danger", style: "margin-left: 10px;"
:javascript
  $("#create-user-btn").click(function() {
    $("#user_birthdate").val($("#day").val() + "-" + $("#month").val() + "-" + $("#year").val());
  });

app/views/users/finish_signup.html.erb
<%= render "home/top_menu" %>
<div id="add-email" class="container">
  <div class='black' style="margin-top: 80px; font-size: 40px; font-weight: 300;">
    Completa el registro
  </div>
  <div class='darkest-gray' style="font-size: 28px; font-weight: 300; margin-bottom: 15px;">
    Datos generales
  </div>
  <div class='row'>
    <div class='col-xs-12'>
      <%= form_for(current_user, :as => 'user', :url => finish_signup_path(current_user), :html => { role: 'form', onsubmit: 'return validateTerms()', class: 'form-horizontal'}) do |f| %>
        <% if @show_errors && current_user.errors.any? %>
          <div id="error_explanation">
            <% current_user.errors.full_messages.each do |msg| %>
              <%= msg %><br>
            <% end %>
          </div>
        <% end %>
        <div class="form-group">
          <div class="col-xs-4">
            <%= f.text_field :username, :autofocus => true, :value => '', class: 'form-control', placeholder: 'Nombre de usuario', required: true %>
          </div>
        </div>
        <%@user.identities.each do |p|%>
          <%if p.provider=="twitter"%>
            <div class="form-group">
              <div class="col-xs-4">
                <%= f.text_field :email, :autofocus => true, :value => '', class: 'form-control', placeholder: 'Correo electrónico', required: true %>  
              </div>
            </div>
          <%end%>
        <%end%>
        <div class='darkest-gray' style="font-size: 28px; font-weight: 300; margin-bottom: 15px;">
          Información demográfica
        </div>
        <%= f.label :birthdate, "Fecha de nacimiento:", style: "font-weight: 600; display: block; margin-top: 5px;" %>
        <%= select_tag :day, options_for_select((1..31).map{|e| [e, e]}), prompt: "Día", class: "form-control", style: "width: 80px; display: inline-block;", required: true %>
        <%= select_tag :month, options_for_select([["Enero", 1], ["Febrero", 2], ["Marzo", 3], ["Abril", 4], ["Mayo", 5], ["Junio", 6], ["Julio", 7], ["Agosto", 8],
          ["Septiembre", 9], ["Octubre", 10], ["Noviembre", 11], ["Diciembre", 12]]), prompt: "Mes", class: "form-control", style: "width: 120px; display: inline-block; margin-left: 5px;", required: true %>
        <%= select_tag :year, options_for_select((1950..2000).map{|e| [e, e]}), prompt: "Año", class: "form-control", style: "width: 80px; display: inline-block; margin-left: 5px;", required: true %>
        <%= f.hidden_field :birthdate %>
        <div class='form-group'>
          <div class='col-xs-4'>
            <%= f.select :gender, options_for_select([["Masculino", "M"], ["Femenino", "F"]], selected: @user.gender), { prompt: "Género" }, class: "form-control", style: "width: 150px; margin-top: 10px; margin-bottom: 15px;", required: true %>
          </div>
        </div>
        <div class="form-group">
          <div class="col-xs-12">
            <%= check_box_tag :accept %>
            <%= "He leído y acepto los <a class='link-orange'>términos y condiciones de uso</a>".html_safe %>
          </div>
        </div>
        <div class="form-group">
          <div class='col-xs-4'>
            <%= f.submit 'Continuar', class: 'btn btn-orange btn-block', style: 'margin-top: 30px;margin-bottom: 30px;' %>
            <%= f.submit "Registrarse", class: 'btn btn-orange', style: 'margin-top: 30px;margin-bottom: 30px;' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <script>
    function validateTerms() {
      $("#user_birthdate").val($("#day").val() + "-" + $("#month").val() + "-" + $("#year").val());
      if(document.getElementById("accept").checked == false) {
        alert("Necesitas aceptar los términos y condiciones de uso");
        return false;
      }
    }
  </script>
</div>

app/views/users/index.html.haml
= render "main/menu"
= render "administration/admin_menu", active: "users"
.row
  .container
    .row
      .form-div.col-xs-12
        = link_to "Agregar administrador", new_user_path, class: "btn btn-orange", style: "margin-top: 30px;"
    .row
      .col-xs-12
        %table.table.table-striped.info-table
          %thead
            %tr
              %th<
                ID
              %th<
                Nombre
              %th<
                Nombre de usuario
              %th<
                Correo electrónico
              %th<
                Género
              %th<
                Fecha de nacimiento
              %th<
                Año de Nacimiento
              %th<
                Nivel
          %tbody
            - @users.order("id asc").each do |user|
              %tr
                %td<
                  = user.id
                %td<
                  = user.name
                %td<
                  = user.username
                %td<
                  = user.email
                %td<
                  = user.gender
                %td<
                  = user.birthdate
                %td<
                  = user.birthdate.to_s.split(//).last(4).join
                %td<
                  = user.is_admin ? "Administrador" : "Normal"

app/views/users/new.html.haml
= render "main/menu"
.row{ style: "margin-top: 60px; padding-bottom: 70px;" }
  .container
    .row
      .col-xs-12.orange{ style: "font-size: 40px; font-weight: 300; margin-top: 30px;" }
        Agregar administrador
    %p#notice= notice
    = render "form"