config/routes.rb
Rails.application.routes.draw do

  get 'comentario/index'

  get 'alumbrado/index'

  get 'parques/index'

  get 'pavimento/index'

  get 'playlist/show'
  
  get 'users/politica'
  

  #se agrega la ruta de devise para users
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  get  "omniauth/:provider/callback"  => "devise_token_auth/omniauth_callbacks#redirect_callbacks"
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], as: :finish_signup
  resources :reports, only: [:show, :new, :create, :update] do
    
    member do
      post "add_vote"
      post "remove_vote"
      post "add_comment"
      post "approve"
      post "re_open"
      post "complete"
      delete "delete"
    end
    
    collection do
      post "add_like" => "reports#add_like"
      post "remove_like" => "reports#remove_like"
    end
  end

  get 'main' => 'main#index'
  get "view_notification" => "main#view_notification"

  namespace :api do
    namespace :v1 do
      #Playlist related routs
      get 'playlist', to: "playlist#show"

      # Report related routes
      get 'reports', to: "report_api#index"
      get 'reports/:id', to: "report_api#show"
      post 'reports', to: "report_api#create"
      put 'reports/:id', to: "report_api#update"
      patch 'reports/:id', to: "report_api#update"
      post 'reports/:id/add_vote', to: 'report_api#add_vote'
      post 'reports/:id/remove_vote', to: 'report_api#remove_vote'
      get 'reports/:id/comments', to: 'report_api#comments'
      post 'reports/:id/add_comment', to: 'report_api#add_comment'
      post 'reports/:id/add_vote', to: 'report_api#add_vote'
      delete 'reports/:id/remove_vote', to: 'report_api#remove_vote'
      post 'reports/:id/propose_as_completed', to: 'report_api#propose_as_completed'
      # Sessions related routes -- DEPRECATED
      # devise_scope :user do
      #   post 'sessions' => 'sessions#create', as: 'login'
      #   delete 'sessions' => 'sessions#destroy', as: 'logout'
      # end
      
      # Contacts related routes
      get 'contacts', to: 'contact_api#index'
      
      # Notifications related routes
      get 'notifications', to: 'notifications_api#recent_notifications'
      post 'notifications/:id/mark_as_read', to: 'notifications_api#mark_as_read'
      
      # Comments related routes
      post 'comments/:id/like', to: 'comment_api#like'
      delete 'comments/:id/unlike', to: 'comment_api#unlike'
      post 'comments/:id/flag', to: 'comment_api#flag'
      
      # User related routes
      post 'user/change_picture', to: 'user_info_api#change_picture'
      get 'user/stats', to: 'user_info_api#stats'

      # Api auth routes
      post 'auth/signin', to: 'auth_api#signin'
      post 'auth/signup', to: 'auth_api#signup'
      post 'auth/finish_signup', to: 'auth_api#finish_signup'
      post 'auth/recover', to: 'auth_api#recover'
      delete 'auth/signout_all', to: 'auth_api#signout_all'
    end
  end  
  

  
  scope "administration" do
    resources :users
    resources :contacts
    resources :reports
    get 'limpia' => "limpia#index"
    get 'pavimento' => "pavimento#index"
    get 'alumbrado' => "alumbrado#index"
    get 'parques' => "parques#index"
    get 'estadistica' => "estadistica#index"
    get 'comentario' => "comentario#index"
    get "reports" => "reports#index"

    
    
  end
  
  root "home#index"
  
end

app/models/report.rb
class Report < ActiveRecord::Base
  include ActionView::Helpers::TextHelper
  require "#{Rails.root}/lib/my_module.rb"
  #include MyModule
  #include ActionView::Helpers::ReportHelper
  # validates :title, presence: true
  validates :latitude, presence: true
  validates :longitude, presence: true
  validates :report_category_id, presence: true
  has_attached_file :image, styles: { :medium => "400x400#" }
  has_attached_file :evidence
  
  # validates_attachment :image, presence: true, content_type: { content_type: ["image/jpeg", "image/gif", "image/png", "image/bmp"] }, size: { less_than: 1.megabytes }
  do_not_validate_attachment_file_type :image
  do_not_validate_attachment_file_type :evidence
  validates_presence_of :image, :message => "Sube una imagen antes de subir tu reporte"

  has_many :comments, dependent: :destroy
  has_many :affectation_votes, dependent: :delete_all
  has_many :activity_records, dependent: :delete_all
  belongs_to :user

  attr_accessor :user_in_question_id

  def image_url
    image.url(:original)
  end
  
  def user_name
    user.username
  end

  def get_report_status
    case status
    when 1
      return "No aprobado"
    when 2
      return "Aprobado"
    when 3
      return "Aprobado"
    when 4
      return "Resuelto"
    else
      return "Error"
    end
  end
  
  def get_report_category
    case report_category_id
    when 1
      return "Limpia"
    when 2
      return "Pavimento"
    when 3
      return "Parques"
    when 4
      return "Alumbrado"
    when 5
      return "Accesibilidad"
    end
  end
  
  def get_oldness
    seconds = (Time.now - created_at).to_i
    if seconds >= 172800
       return pluralize((seconds / 172800), "días")
    elsif seconds >= 86400
      return pluralize((seconds / 86400), "día")
    elsif seconds >= 3600
      return pluralize((seconds / 3600), "hora")
    elsif seconds >= 60
      return pluralize((seconds / 60), "minuto")
    else
      return pluralize(seconds, "segundo")
    end
  end
  
  def votes_conversion
    if affectation_votes.count > 1000000
      return "#{(affectation_votes.count / 1000000.0).round(2)} M"
    elsif affectation_votes.count > 1000
      return "#{(affectation_votes.count / 1000.0).round(2)} k"
    else
      return affectation_votes.count
    end
  end

  def comments_conversion
    if comments.count > 1000000
      return "#{(comments.count / 1000000.0).round(2)} M"
    elsif comments.count > 1000
      return "#{(comments.count / 1000.0).round(2)} k"
    else
      return comments.count
    end
  end

  def user_is_affected
    affectation_votes.where(user_id: self.user_in_question_id).count > 0 ? true : false
  end
  
   def get_address          
     query = "#{latitude},#{longitude}"
     #Rails.logger.info "ID REPORTE: #{id} Solicitas Info !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
     variable = "{ 'position' : {'lat' : #{latitude} , 'lng' : #{longitude}} };"
     #variable = my_method
     return variable
  end
 
 
 filterrific(
  default_filter_params: { sorted_by: 'id desc' },
  available_filters: [
    :sorted_by,
    :search_query,
    :with_report_id,
    ]
  )
# define ActiveRecord scopes for
# :search_query, :sorted_by, :with_country_id, and :with_created_at_gte
 
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except: [:show]
  before_filter :user_is_admin?, only: [:index]
  before_filter :valid_report?, only: [:show]
  require 'rest_client'

  # GET /reports
  # GET /reports.json
  def index
    @reports = Report.all
  end
  
  def add_comment    
    puts "--------------------------------------------------------------------------------"
    @comment = Comment.create(content: "#{"@#{User.find(params[:reply_to_id]).username} - " if params[:reply_to_id]}#{params[:content]}", report_id: params[:id], user_id: current_user.id)
    ActivityRecord.create(activity_type: 4, user_id: current_user.id, report_id: params[:id], user_to_notificate: Report.find(params[:id]).user_id)
    puts 'Finaliza la transaccion'
    usuario = Report.find(params[:id]).username
    
    usuarionuevo = Report.find(params[:id]).user_id
    usuariototal = User.find_by(id: usuarionuevo )
    puts usuariototal.username
    puts usuarionuevo
    puts usuario
    puts current_user.username 
      if current_user.username != usuario
       #Se genera el armado del cuerpo para el REST 
       #Bloque de notificaciones para usuarios que comentan en el reporte 
        # RestClient.post('https://jbossunifiedpush1-denialtorres.rhcloud.com/ag-push/rest/sender/', :autorization => "Basic ODgyZDQ5MTUtMTA5Yy00MGM5LWI4NmQtYWU2YTI2NmY5ZmU4OjI2YzU3MjEwLTg2OTktNGJmYS1iYWE4LWI3M2I2OGFlZWEyYw==")
        request_body_map = {
         :alias => [usuariototal.username], 
         :message => { :alert => current_user.username + " comentó tu reporte"}
          }
   
   
           RestClient.post("https://jbossunifiedpush1-denialtorres.rhcloud.com/ag-push/rest/sender/",
                              request_body_map.to_json,    # Encode the entire body as JSON
                              {:authorization => "Basic MzQzMzc4YWUtYzYxMi00Mzg2LWJjNzktN2EyNjVmM2U5NTRhOmU4YzBlMGQxLTNhNzMtNGM0OS04OWI3LThiZTU1ODQzNDRmNw==",
                               :content_type => 'application/json',
                               :accept => 'application/json'})
  #------------------------------------------------------------------------------------------------   
      end
                         
    if params[:reply_to_id]
      ActivityRecord.create(activity_type: 6, user_id: current_user.id, report_id: params[:id], user_to_notificate: params[:reply_to_id])
      
      puts "comentario de respuestas"
      aveter = ActivityRecord.find_by(user_to_notificate: params[:reply_to_id])
      
      puts aveter.user_to_notificate 
      usereo = User.find_by(id: aveter.user_to_notificate )
      puts usereo.username 
      usuariorespuesta = usereo.username 
    # RestClient.post('https://jbossunifiedpush1-denialtorres.rhcloud.com/ag-push/rest/sender/', :autorization => "Basic ODgyZDQ5MTUtMTA5Yy00MGM5LWI4NmQtYWU2YTI2NmY5ZmU4OjI2YzU3MjEwLTg2OTktNGJmYS1iYWE4LWI3M2I2OGFlZWEyYw==")
    #Bloque de notificaciones para usuarios que responden comentarios
    request_body_map = {
   :alias => [usuariorespuesta], 
   :message => { :alert => current_user.username + " a respondido a tu comentario"}
  }
   
   
    RestClient.post("https://jbossunifiedpush1-denialtorres.rhcloud.com/ag-push/rest/sender/",
                              request_body_map.to_json,    # Encode the entire body as JSON
                              {:authorization => "Basic MzQzMzc4YWUtYzYxMi00Mzg2LWJjNzktN2EyNjVmM2U5NTRhOmU4YzBlMGQxLTNhNzMtNGM0OS04OWI3LThiZTU1ODQzNDRmNw==",
                               :content_type => 'application/json',
                               :accept => 'application/json'})
  #------------------------------------------------------------------------------------------------     
      
      
    end
  end
  
  def add_vote
    puts "////////////////////////////////////////// Aqui pones si afecto tu reporte //////////////////////////////////////////////////////////////////////"
    AffectationVote.create(user_id: current_user.id, report_id: params[:id]) if AffectationVote.where(user_id: current_user.id).where(report_id: params[:id]).count == 0
    ActivityRecord.create(activity_type: 3, user_id: current_user.id, report_id: params[:id],
      user_to_notificate: Report.find(params[:id]).user_id) if ActivityRecord.where(report_id: params[:id]).where(user_id: current_user.id).where(activity_type: 3).count == 0
    @votes = AffectationVote.where(report_id: params[:id]).count
    usuarionuevo = Report.find(params[:id]).user_id
    usuariototal = User.find_by(id: usuarionuevo )
    puts usuariototal.username
    puts usuarionuevo
    puts current_user.username 
    
     if current_user.username != usuariototal.username
    #------------Mandas notificacion de que a otro usuario tambien le afecta tu reporte
         request_body_map = {
        :alias => [usuariototal.username], 
        :message => { :alert => current_user.username + " mencionó que también le afecta tu reporte"}
        }
   
   
        RestClient.post("https://jbossunifiedpush1-denialtorres.rhcloud.com/ag-push/rest/sender/",
                              request_body_map.to_json,    # Encode the entire body as JSON
                              {:authorization => "Basic MzQzMzc4YWUtYzYxMi00Mzg2LWJjNzktN2EyNjVmM2U5NTRhOmU4YzBlMGQxLTNhNzMtNGM0OS04OWI3LThiZTU1ODQzNDRmNw==",
                               :content_type => 'application/json',
                               :accept => 'application/json'})
  #------------------------------------------------------------------------------------------------     
    end  
    
  end
  
  def remove_vote
    vote = AffectationVote.where(user_id: current_user.id).where(report_id: params[:id]).first
    vote.destroy if vote
    @votes = AffectationVote.where(report_id: params[:id]).count
  end
  
  
  #//LIKE A COMENTARIO
  def add_like
    puts "Aqui le das like a un comentario"
    Like.create(user_id: current_user.id, comment_id: params[:comment_id]) if Like.where(user_id: current_user.id).where(comment_id: params[:comment_id]).count == 0
    @likes = Like.where(comment_id: params[:comment_id]).count
    #ActivityRecord.create(activity_type: 4, user_id: current_user.id, report_id: params[:id], user_to_notificate: Report.find(params[:id]).user_id)
    puts "Aqui le das like a un comentario - hola "
    #usuarionuevo = Report.find(params[:id]).user_id
    #usuarionuevo = Report.find(params[:id])
    usuariototal = User.find_by(id: 2 )
    puts usuariototal.username
    puts "Usuario que da like " + current_user.username 
    puts "Usuario que recibe like " + usuariototal.username
    #usuarionuevo = Like.find(params[:id]).user_id
   
    puts current_user.username 
    #puts Like.user_id
  #     #---------------------------darle like a un comentario---------------------------------------# 
  #     request_body_map = {
  # :alias => ["user"], 
  # :message => { :alert => "A " + current_user.username  + " le gusta tu comentario"}
  # }
   
   
  #   RestClient.post("https://jbossunifiedpush1-denialtorres.rhcloud.com/ag-push/rest/sender/",
  #                             request_body_map.to_json,    # Encode the entire body as JSON
  #                             {:authorization => "Basic MzQzMzc4YWUtYzYxMi00Mzg2LWJjNzktN2EyNjVmM2U5NTRhOmU4YzBlMGQxLTNhNzMtNGM0OS04OWI3LThiZTU1ODQzNDRmNw==",
  #                             :content_type => 'application/json',
  #                             :accept => 'application/json'})
  #   #---------------------------------------------------------------------------------------------------------
  end
  
  def remove_like
    like = Like.where(user_id: current_user.id).where(comment_id: params[:comment_id]).first
    like.destroy if like
    @likes = Like.where(comment_id: params[:comment_id]).count
  end
  
  def approve
    puts "////////////////////////////////////////// Aqui es donde se aprueba el reporte //////////////////////////////////////////////////////////////////////"
    report = Report.find(params[:id])
    report.status = 2
    report.save
    ActivityRecord.create(activity_type: 2, user_id: current_user.id, report_id: params[:id], user_to_notificate: report.user_id)
    #Aqui buscas enviar notificacion a usuarios de la dependencia
    if report.report_category_id == 1
      User.where("is_admin= ? AND departamento= ?",true,1).each do |user|
        ActivityRecord.create(activity_type: 10, user_id: current_user.id, report_id:  params[:id], user_to_notificate: user.id)
      end
    end  
    if report.report_category_id == 2
      User.where("is_admin= ? AND departamento= ?",true,2).each do |user|
        ActivityRecord.create(activity_type: 11, user_id: current_user.id, report_id:  params[:id], user_to_notificate: user.id)
      end
    end
    if report.report_category_id == 3
      User.where("is_admin= ? AND departamento= ?",true,3).each do |user|
        ActivityRecord.create(activity_type: 12, user_id: current_user.id, report_id:  params[:id], user_to_notificate: user.id)
      end
    end
    if report.report_category_id == 4
      User.where("is_admin= ? AND departamento= ?",true,4).each do |user|
        ActivityRecord.create(activity_type: 13, user_id: current_user.id, report_id:  params[:id], user_to_notificate: user.id)
      end
    end 
    check_if_user_leveled_up(Report.find(params[:id]).user_id, report.id)
    usuarionotificado = ActivityRecord.find_by(user_to_notificate: report.user_id)
    puts "///////////////////////////////////"
    puts usuarionotificado.user_to_notificate 
    usuarionotificado1 = User.find_by(id: usuarionotificado.user_to_notificate )
    puts usuarionotificado1.username 
    usuarioreporte = usuarionotificado1.username 
    #---------------------------Mandar notificacion para avisar que fue aprobado el reporte----------------------------------------# 
      request_body_map = {
   :alias => [usuarioreporte], 

app/helpers/reports_helper.rb
module ReportsHelper
  def color_label(status)
    case status
    when 1
      return "lbl lbl-red"
    when 2
      return "lbl lbl-green"
    when 3
      return "lbl lbl-light-blue"
    when 4
      return "lbl lbl-blue"
    end
  end
  
  def invocas_metodo
    return "gatito"
  end
end

app/views/reports/_form.html.haml
- if (@report.errors.any?)
  .alert.alert-danger
    %strong ERROR!
    = @report.errors.messages[:image]
= form_for @report do |f|
  .row
    .col-xs-8
      .panel.panel-default
        .panel-heading
          %h3.panel-title
            %i.icomoon-marcador.light-gray.icon-panel
            Ubicación
        #map-canvas.panel-body.panel-no-padding
    .col-xs-4
      .panel.panel-default
        .panel-heading
          %h3.panel-title
            %i.glyphicon.glyphicon-camera.light-gray.icon-panel
            Fotografía
        .report-image.panel-body.panel-no-padding
          %img{ width: "100%" }
      .panel.panel-default
        .panel-heading
          %h3.panel-title
            %i.glyphicon.glyphicon-list-alt.light-gray.icon-panel
            Detalles
        .panel-body
          = f.hidden_field :latitude, class: "form-control"
          = f.hidden_field :longitude, class: "form-control"
          .form-group
            = f.label :title, "Título"
            = f.text_field :title, class: "form-control"
          .form-group
            = f.label :report_category_id, "Categoría"
            = f.select :report_category_id, options_for_select([ ["Limpia", 1], ["Pavimento", 2], ["Parques", 3], ["Alumbrado", 4], ["Accesibilidad", 5] ], selected: @report.report_category_id), {}, class: "form-control"
          .form-group
            = f.label :details, "Otros detalles"
            = f.text_area :details, class: "form-control", resize: "none";
          .form-group
            = f.label :image, "Imagen"
            = f.file_field :image
          = f.submit 'Crear', class: "btn btn-orange col-xs-12", style: "margin-top: 30px;"
          
:javascript
  $(document).ready(function() {
    var preview = $(".report-image img");
    $("#report_image").change(function(event) {
      var input = $(event.currentTarget);
      var file = input[0].files[0];
      var reader = new FileReader();
      reader.onload = function(e) {
        image_base64 = e.target.result;
        preview.attr("src", image_base64);
        preview.attr("alt", "Vista previa no disponible");
      };
      reader.readAsDataURL(file);
    });
  });

app/views/reports/add_comment.js.erb
$("#comments").prepend("<div class='comment row'>\
    <div class='col-xs-2 text-center'>\
      <% if current_user.avatar.url != "/avatars/original/missing.png" %>\
      <i class='icomoon-yo orange' style='position: relative; top: 7px; font-size: 35px;'></i>\
      <% else %>\
      <i class='icomoon-yo dark-gray' style='position: relative; top: 7px; font-size: 35px;'></i>\
      <% end %>\
    </div>\
    <div class='col-xs-10'>\
      <div class='black'>\
        <span style='font-weight: 700;'><%= current_user.username %></span>\
        <span style='font-size: 12px;'><%= "hace #{get_oldness((Time.now - @comment.created_at).to_i)}"%></span>\
        <span id='likes-<%= @comment.id %>'>(<%= Like.where(comment_id: @comment.id).count %>)</span>\
      </div>\
      <div><%= @comment.content %></div>\
      <div class='comment-buttons'>\
        <a class='comment-btn' href='#'><i class='icomoon-like'></i></a>\
        <a class='comment-btn' href='#'><i class='icomoon-reportar'></i></a>\
      </div>\
    </div>\
  </div>");

app/views/reports/add_like.js.erb
$("#like-btn-<%= params[:comment_id] %>").html('<%= link_to "<i class=\"icomoon-like\"></i>".html_safe, remove_like_reports_path(comment_id: params[:comment_id]), class: "comment-btn unlike", remote: true, method: :post %>');
$("#likes-<%= params[:comment_id] %>").html('(<%= @likes %>)');

app/views/reports/add_vote.js.erb
$("#affectation-link").html('<%= link_to "<i class=\"icomoon-no-afecta icon-details red\"></i>".html_safe, remove_vote_report_path, method: :post, remote: true %>');
$("#affectation-text").html("No afecta");
$("#affected-number").html('<%= qty_conversion(@votes) %>');
$("#affected-text").html('<%= @votes == 1 ? "ciudadano afectado" : "ciudadanos afectados" %>');

app/views/reports/edit.html.haml
%h1 Editing report

= render 'form'

= link_to 'Show', @report
\|
= link_to 'Back', reports_path

app/views/reports/index.html.haml
= render "main/menu"
= render "administration/admin_menu", active: "reports"
.row
  .container
    .row
      .col-xs-12
        %table.table.table-striped.info-table
          %thead
            %tr
              %th<
                ID
              %th<
                Título
              %th<
                Estado
              %th<
                Creado por
              %th<
                Fecha
              %th<
                Categoría
              %th<
                Descripción
              %th<
              
              %th
          %tbody
            - @reports.order("id desc").each do |report|
              %tr
                %td<
                  = report.id
                %td<
                  = report.title
                %td<
                  %span{ class: color_label(report.status) }
                    = get_report_status(report.status)
                %td<
                  = report.user.username
                %td<
                  = report.created_at.localtime.strftime('%d-%m-%Y')
                %td<
                  = get_report_category(report.report_category_id)
                %td<
                  = report.details
                %td<
                  = link_to "Ver", report, class: "btn btn-orange btn-xs"
                %td<
                  = link_to 'Eliminar', delete_report_path(report), method: :delete , class: "btn btn-danger btn-xs", :data => { :confirm => 'Estas Seguro?' }

app/views/reports/new.html.erb
<% content_for :head do %>
  <script src="https://maps.googleapis.com/maps/api/js?language=es&amp;key=AIzaSyA47C4qJmfWX1vVgsj0plfElJPuBAnb46Y"></script>
<% end %>
<%= render "main/menu" %>
<div class="row" style="margin-top: 60px;">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <p class="report-title">Crear reporte</p>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  var map;
  var home = new google.maps.LatLng(31.7, -106.4);
  var markers = [];
  
  var marker_selected = {
    url: "<%= image_url "marker-selected.png" %>",
    size: new google.maps.Size(35, 47),
    origin: new google.maps.Point(0, 0),
    anchor: new google.maps.Point(18, 47)
  };

  function initialize() {
    var mapDiv = document.getElementById("map-canvas");
    
    var mapOptions = {
      zoom: 12,
      center: home,
      disableDefaultUI: true,
      zoomControl: true,
      zoomControlOptions: {
        style: google.maps.ZoomControlStyle.SMALL
      }
    };

    map = new google.maps.Map(mapDiv, mapOptions);
    
    google.maps.event.addListener(map, "click", function(event) {
      document.getElementById("report_longitude").value = event.latLng.lng();
      document.getElementById("report_latitude").value = event.latLng.lat();
      deleteMarkers();
      addMarker(event.latLng);
    });
  }

  function addMarker(location) {
    var marker = new google.maps.Marker({
      position: location,
      icon: marker_selected,
      map: map
    });
    
    markers.push(marker);
  }

  function setAllMap(map) {
    for (var i = 0; i < markers.length; i++) {
      markers[i].setMap(map);
    }
  }

  function clearMarkers() {
    setAllMap(null);
  }

  function deleteMarkers() {
    clearMarkers();
    markers = [];
  }

  google.maps.event.addDomListener(window, "load", initialize);
</script>

app/views/reports/remove_like.js.erb
$("#like-btn-<%= params[:comment_id] %>").html('<%= link_to "<i class=\"icomoon-like\"></i>".html_safe, add_like_reports_path(comment_id: params[:comment_id]), class: "comment-btn", remote: true, method: :post %>');
$("#likes-<%= params[:comment_id] %>").html('(<%= @likes %>)');

app/views/reports/remove_vote.js.erb
$("#affectation-link").html('<%= link_to "<i class=\"icomoon-me-afecta icon-details red\"></i>".html_safe, add_vote_report_path, method: :post, remote: true %>');
$("#affectation-text").html("Me afecta");
$("#affected-number").html('<%= qty_conversion(@votes) %>');
$("#affected-text").html('<%= @votes == 1 ? "ciudadano afectado" : "ciudadanos afectados" %>');