config/routes.rb
Rails.application.routes.draw do

  get 'comentario/index'

  get 'alumbrado/index'

  get 'parques/index'

  get 'pavimento/index'

  get 'playlist/show'
  
  get 'users/politica'
  

  #se agrega la ruta de devise para users
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  get  "omniauth/:provider/callback"  => "devise_token_auth/omniauth_callbacks#redirect_callbacks"
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], as: :finish_signup
  resources :reports, only: [:show, :new, :create, :update] do
    
    member do
      post "add_vote"
      post "remove_vote"
      post "add_comment"
      post "approve"
      post "re_open"
      post "complete"
      delete "delete"
    end
    
    collection do
      post "add_like" => "reports#add_like"
      post "remove_like" => "reports#remove_like"
    end
  end

  get 'main' => 'main#index'
  get "view_notification" => "main#view_notification"

  namespace :api do
    namespace :v1 do
      #Playlist related routs
      get 'playlist', to: "playlist#show"

      # Report related routes
      get 'reports', to: "report_api#index"
      get 'reports/:id', to: "report_api#show"
      post 'reports', to: "report_api#create"
      put 'reports/:id', to: "report_api#update"
      patch 'reports/:id', to: "report_api#update"
      post 'reports/:id/add_vote', to: 'report_api#add_vote'
      post 'reports/:id/remove_vote', to: 'report_api#remove_vote'
      get 'reports/:id/comments', to: 'report_api#comments'
      post 'reports/:id/add_comment', to: 'report_api#add_comment'
      post 'reports/:id/add_vote', to: 'report_api#add_vote'
      delete 'reports/:id/remove_vote', to: 'report_api#remove_vote'
      post 'reports/:id/propose_as_completed', to: 'report_api#propose_as_completed'
      # Sessions related routes -- DEPRECATED
      # devise_scope :user do
      #   post 'sessions' => 'sessions#create', as: 'login'
      #   delete 'sessions' => 'sessions#destroy', as: 'logout'
      # end
      
      # Contacts related routes
      get 'contacts', to: 'contact_api#index'
      
      # Notifications related routes
      get 'notifications', to: 'notifications_api#recent_notifications'
      post 'notifications/:id/mark_as_read', to: 'notifications_api#mark_as_read'
      
      # Comments related routes
      post 'comments/:id/like', to: 'comment_api#like'
      delete 'comments/:id/unlike', to: 'comment_api#unlike'
      post 'comments/:id/flag', to: 'comment_api#flag'
      
      # User related routes
      post 'user/change_picture', to: 'user_info_api#change_picture'
      get 'user/stats', to: 'user_info_api#stats'

      # Api auth routes
      post 'auth/signin', to: 'auth_api#signin'
      post 'auth/signup', to: 'auth_api#signup'
      post 'auth/finish_signup', to: 'auth_api#finish_signup'
      post 'auth/recover', to: 'auth_api#recover'
      delete 'auth/signout_all', to: 'auth_api#signout_all'
    end
  end  
  

  
  scope "administration" do
    resources :users
    resources :contacts
    resources :reports
    get 'limpia' => "limpia#index"
    get 'pavimento' => "pavimento#index"
    get 'alumbrado' => "alumbrado#index"
    get 'parques' => "parques#index"
    get 'estadistica' => "estadistica#index"
    get 'comentario' => "comentario#index"
    get "reports" => "reports#index"

    
    
  end
  
  root "home#index"
  
end

app/controllers/comentario_controller.rb
class ComentarioController < ApplicationController
  def index
    @comentarios = Comment.where("user_id != ?",833).last(20).reverse  
  end
end

app/helpers/comentario_helper.rb
module ComentarioHelper
end

app/views/comentario/index.html.haml
%script{:src => "//yociudadano.com.mx/assetsexternos/jquery.dataTables.min.js"}
%script{:src => "//yociudadano.com.mx/assetsexternos/horizBarChart.js"}
:javascript
  $(document).ready(function(){
  $('.chart').horizBarChart({
    selector: '.bar',
    speed: 3000
  });
  });
:css
  @import url(https://fonts.googleapis.com/css?family=Montserrat);
  .chart {
      zoom: 1;
      width: 90%
  }
  
  .chart:after {
      clear: both;
      content: '.';
      display: block;
      height: 0;
      visibility: hidden
  }
  
  .chart li {
      display: block;
      height: 40px;
      margin-top: 3px;
      position: relative
  }
  
  .chart li:before {
      color: #fff;
      content: attr(title);
      left: 5px;
      position: absolute
  }
  
  .chart li.title:before {
      color: black;
      font-weight: bold;
      left: 0;
      font-family: Montserrat;
      font-size: 30px;
  }
  
  .chart li:first-child {
      margin-top: 0
  }
  
  .chart li .bar {
      background: #F89839;
      height: 100%
  }
  
  .chart li .number {
      color: black;
      font-size: 18px;
      font-weight: bold;
      padding-left: 5px;
      position: absolute;
      top: -2px
  }
  
  .chart li.past .bar {
      background: #aaa
  }
  
  .chart li.past .number {
      color: #000
  }
  
  @media screen and (max-width: 480px) {
      .chart li {
          height: auto
      }
      .chart li:before {
          color: black;
          display: block;
          left: 0;
          position: relative
      }
      .chart li.title:before {
          border-bottom: 1px solid
      }
      .chart li .bar {
          height: 23px
      }
      .chart li .number {
          display: block;
          left: 0 !important;
          padding-left: 0;
          position: relative;
          top: -8px
      }
  }
  
  
  .chart li.past #seccion1{
      background: #57C1AF;
  }
  
  .chart li.past #seccion2{
      background: #EE2263;
  }
  
  .chart li.past #seccion3{
      background: #B2A095;
  }
  
  .chart li.past #seccion4{
      background: #C39A6B;
  }
  
  
  
  .past{
   font-size: 25px;
   font-family: 'Montserrat';
  }
= javascript_include_tag "//www.google.com/jsapi", "chartkick"
= render "main/menu"
= render "administration/admin_menu", active: "comentarios"
.row
  .container
    .row
      .col-xs-12
        %table.table.table-striped.info-table
          %thead
            %tr
              %th<
                ID
              %th<
                Comentario
              %th<
                Autor
              %th<
                Fecha
              %th<
                Reporte
              %th<
          %tbody
            - @comentarios.each do |comentario|
              %tr
                %td<
                  = comentario.id
                %td<
                  = comentario.content
                %td<
                  = get_report_username(comentario.user_id)
                %td<
                  = comentario.created_at.localtime.strftime('%d-%m-%Y')
                %td<
                  = link_to "Ver", report_path(comentario.report_id), class: "btn btn-orange btn-xs"
                %td<
                //   = link_to 'Eliminar', delete_report_path(report), method: :delete , class: "btn btn-danger btn-xs", :data => { :confirm => 'Estas Seguro?' }
%h1 Comentario#index
%p Find me in app/views/comentario/index.html.haml